### ISSUE TITLE
App crashing with null safety version

### ISSUE THREAD

**Issue by Alan-Gomes** [moodio/msal-flutter#25]
We are experiencing crashes when using this lib in the current null safety version:

```
E/AndroidRuntime( 7973): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime( 7973): 	at com.microsoft.identity.client.internal.CommandParametersAdapter.createCommandParameters(CommandParametersAdapter.java:65)
E/AndroidRuntime( 7973): 	at com.microsoft.identity.client.PublicClientApplication.create(PublicClientApplication.java:913)
E/AndroidRuntime( 7973): 	at com.microsoft.identity.client.PublicClientApplication.access$000(PublicClientApplication.java:202)
E/AndroidRuntime( 7973): 	at com.microsoft.identity.client.PublicClientApplication$3.run(PublicClientApplication.java:365)
E/AndroidRuntime( 7973): 	at java.lang.Thread.run(Thread.java:923)
```

The method causing this is
```
await PublicClientApplication.createPublicClientApplication(
      azureAppID,
      authority: _authority,
    )
```

**Comment by Alan-Gomes** [comment]
After looking up in the https://github.com/AzureAD/microsoft-authentication-library-for-android source code. I found out that the lib crashes when some of the properties are not set:

```
"power_opt_check_for_network_req_enabled": true,
"web_view_zoom_enabled": false,
"web_view_zoom_controls_enabled": false,
```

After setting those properties, everything worked.

**Comment by kranfix** [comment]
@Alan-Gomes I'm facing the same problem, but I don't know which file edit. Could you tell me the filename, please?

**Comment by NightkingCH** [comment]
Came across this problem today as well. This belongs to the msal_config. You find it here: <PATH_TO_YOUR_APP>\android\app\src\main\res\raw\msal_default_config.json

**Comment by johnzhu123** [comment]
still got a similar error even I add 
```json
"power_opt_check_for_network_req_enabled": true,
"web_view_zoom_enabled": false,
"web_view_zoom_controls_enabled": false,
```
to my msal_default_config.json

the error look like this

```
I/xample.iconsole( 5745): Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
W/Parcel  ( 5745): Expecting binder but got null!
I/flutter ( 5745): initializing pca
D/MsalFlutter( 5745): Getting the created listener
E/AndroidRuntime( 5745): FATAL EXCEPTION: Thread-4
E/AndroidRuntime( 5745): Process: com.example.iconsole, PID: 5745
E/AndroidRuntime( 5745): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime( 5745): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfigurationInternal(PublicClientApplicationConfigurationFactory.java:96)
E/AndroidRuntime( 5745): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:60)
E/AndroidRuntime( 5745): 	at com.microsoft.identity.client.PublicClientApplication$3.run(PublicClientApplication.java:366)
E/AndroidRuntime( 5745): 	at java.lang.Thread.run(Thread.java:1012)
I/Process ( 5745): Sending signal. PID: 5745 SIG: 9
Lost connection to device.

Exited.
```

**Comment by johnzhu123** [comment]
FYI
just add these two line
```
"handle_null_taskaffinity": false,
 "authorization_in_current_task": false,
```
